## Simple techniques for Data preprocessing

In [7]:
import numpy as np 
import pandas as pd

### Generating random data

In [8]:
np.random.seed(42)
def createdata():
    data ={
        "Age":np.random.randint(18,70,size=20),
        "Salary":np.random.randint(30000,120000,size=20),
        "Purchased":np.random.choice([0,1],size=20),
        "Gender":np.random.choice(["male","female"],size=20),
        "City":np.random.choice(["New York","San Francisco","Los Angeles"],size=20)
        }
    df = pd.DataFrame(data)
    return df
df= createdata()
df.head(10)

   Age  Salary  Purchased  Gender           City
0   56   92955          1  female  San Francisco
1   69   94925          0  female  San Francisco
2   46   97969          0    male       New York
3   32   35311          0  female    Los Angeles
4   60  113104          0    male  San Francisco
5   25   83707          0  female  San Francisco
6   38  115305          0    male  San Francisco
7   56   58693          0  female  San Francisco
8   36  101932          0    male  San Francisco
9   40   55658          1    male  San Francisco

In [9]:
df.shape

(20, 5)

### when we have some missing values

In [10]:
# Introduce some missing values 
df.loc[4,"Age"] = np.nan
df.loc[10,"Salary"]= np.nan
df.head(11)

     Age    Salary  Purchased  Gender           City
0   56.0   92955.0          1  female  San Francisco
1   69.0   94925.0          0  female  San Francisco
2   46.0   97969.0          0    male       New York
3   32.0   35311.0          0  female    Los Angeles
4    NaN  113104.0          0    male  San Francisco
5   25.0   83707.0          0  female  San Francisco
6   38.0  115305.0          0    male  San Francisco
7   56.0   58693.0          0  female  San Francisco
8   36.0  101932.0          0    male  San Francisco
9   40.0   55658.0          1    male  San Francisco
10  28.0       NaN          1  female    Los Angeles

In [11]:
#  simple Imputaion(mean, median, mode)
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
df.head(11)

          Age    Salary  Purchased  Gender           City
0   56.000000   92955.0          1  female  San Francisco
1   69.000000   94925.0          0  female  San Francisco
2   46.000000   97969.0          0    male       New York
3   32.000000   35311.0          0  female    Los Angeles
4   40.263158  113104.0          0    male  San Francisco
5   25.000000   83707.0          0  female  San Francisco
6   38.000000  115305.0          0    male  San Francisco
7   56.000000   58693.0          0  female  San Francisco
8   36.000000  101932.0          0    male  San Francisco
9   40.000000   55658.0          1    male  San Francisco
10  28.000000   92955.0          1  female    Los Angeles

In [12]:
df_dropped = df.dropna()
df_dropped.head()

         Age    Salary  Purchased  Gender           City
0  56.000000   92955.0          1  female  San Francisco
1  69.000000   94925.0          0  female  San Francisco
2  46.000000   97969.0          0    male       New York
3  32.000000   35311.0          0  female    Los Angeles
4  40.263158  113104.0          0    male  San Francisco

In [13]:
df_dropped.shape

(20, 5)

In [15]:
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=3)
df[["Age","Salary"]]=knn_imputer.fit_transform(df[["Age","Salary"]])

In [16]:
df.head(10)

         Age    Salary  Purchased  Gender           City
0  56.000000   92955.0          1  female  San Francisco
1  69.000000   94925.0          0  female  San Francisco
2  46.000000   97969.0          0    male       New York
3  32.000000   35311.0          0  female    Los Angeles
4  40.263158  113104.0          0    male  San Francisco
5  25.000000   83707.0          0  female  San Francisco
6  38.000000  115305.0          0    male  San Francisco
7  56.000000   58693.0          0  female  San Francisco
8  36.000000  101932.0          0    male  San Francisco
9  40.000000   55658.0          1    male  San Francisco